services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  kafka:
    image: confluentinc/cp-kafka:7.5.0
    ports:
      - ${KAFKA_PORT:?error}:${KAFKA_PORT:?error}
      - 9093:9093
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://${KAFKA_ADDR:?error},PLAINTEXT_HOST://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: /bin/kafka-cluster cluster-id --bootstrap-server ${KAFKA_ADDR:?error} || exit 1
      interval: 10s
      timeout: 60s
      retries: 60
  kafka-setup:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER_ID: ignored
      KAFKA_ZOOKEEPER_CONNECT: ignored
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
              cub kafka-ready -b ${KAFKA_ADDR} 1 20 && \
              kafka-topics --create --if-not-exists --partitions 1 --replication-factor 1 --bootstrap-server ${KAFKA_ADDR} --topic ${KAFKA_TOPIC} && \
              echo Waiting 60 seconds for Connect to be ready... && \
              sleep 60'"
