services:
  validator:
    build:
      context: ../src/validator
      dockerfile: Dockerfile
    ports:
      - 4040:4040
    depends_on:
      kafka:
        condition: service_healthy
    environment:
      KAFKA_ADDR: ${KAFKA_ADDR:?error}
      KAFKA_TOPIC: ${KAFKA_TOPIC:?error}
      HADOOP_URI: ${HADOOP_URI:?error}
      HADOOP_DATA_FOLDER: ${HADOOP_DATA_FOLDER:?error}
